import React from 'react';
import {interpolate, useCurrentFrame} from 'remotion';
import {C, FONT, R, SHADOW} from './tokens';
import {EASE} from '../lib/motion';

/**
 * A pointer that travels between waypoints and clicks.
 *
 * Two things make a fake cursor look fake, and both are avoided here. The
 * first is constant speed: a real hand accelerates out of rest and decelerates
 * hard into the target, which is `EASE.out` per leg rather than a single tween
 * across the whole path. The second is a click that fires with no settle -
 * the pointer here arrives, holds for a beat, then the ripple goes.
 *
 * Waypoints are in 1920x1080 film coordinates, so they can be read straight off
 * a rendered still.
 */
export type Waypoint = {at: number; x: number; y: number; click?: boolean};

export const Cursor: React.FC<{path: Waypoint[]; hideAfter?: number}> = ({path, hideAfter}) => {
	const frame = useCurrentFrame();
	if (!path.length) return null;

	let x = path[0].x;
	let y = path[0].y;

	for (let i = 0; i < path.length; i++) {
		const p = path[i];
		if (frame >= p.at) {
			x = p.x;
			y = p.y;
			const next = path[i + 1];
			if (next && frame < next.at) {
				const t = interpolate(frame, [p.at, next.at - 6], [0, 1], {
					extrapolateLeft: 'clamp',
					extrapolateRight: 'clamp',
					easing: EASE.out,
				});
				x = p.x + (next.x - p.x) * t;
				y = p.y + (next.y - p.y) * t;
			}
		}
	}

	const clicks = path.filter((p) => p.click);
	const vis = hideAfter
		? interpolate(frame, [hideAfter, hideAfter + 12], [1, 0], {
				extrapolateLeft: 'clamp',
				extrapolateRight: 'clamp',
			})
		: 1;

	const appear = interpolate(frame, [path[0].at - 8, path[0].at], [0, 1], {
		extrapolateLeft: 'clamp',
		extrapolateRight: 'clamp',
	});

	return (
		<>
			{clicks.map((c) => {
				const t = interpolate(frame, [c.at, c.at + 26], [0, 1], {
					extrapolateLeft: 'clamp',
					extrapolateRight: 'clamp',
					easing: EASE.out,
				});
				if (t <= 0 || t >= 1) return null;
				return (
					<div
						key={`${c.at}-${c.x}`}
						style={{
							position: 'absolute',
							left: c.x - 34,
							top: c.y - 34,
							width: 68,
							height: 68,
							borderRadius: 999,
							border: `2px solid ${C.brand}`,
							opacity: (1 - t) * 0.85,
							transform: `scale(${0.3 + t * 0.9})`,
							pointerEvents: 'none',
						}}
					/>
				);
			})}

			<svg
				width={30}
				height={38}
				viewBox="0 0 30 38"
				style={{
					position: 'absolute',
					left: x,
					top: y,
					opacity: vis * appear,
					filter: 'drop-shadow(0 3px 7px rgba(31,36,48,0.34))',
					pointerEvents: 'none',
				}}
			>
				<path d="M3 2.2 3 27.4l6.2-6.1 4.1 9.6 5.2-2.2-4-9.4 8.6-.1Z" fill="#fff" stroke="#1F2430" strokeWidth="1.9" strokeLinejoin="round" />
			</svg>
		</>
	);
};

/**
 * A generated artefact, presented the way the console presents one: it grows
 * out of the task that produced it rather than cutting to a new scene, so the
 * causal link between "a task ran" and "this document exists" stays on screen.
 *
 * `zoom` runs a slow push into the body once the sheet has landed, which is
 * what Ashley asked for - open the document, then go in on the part that
 * carries the argument.
 */
export const ArtifactSheet: React.FC<{
	at: number;
	title: string;
	subtitle?: string;
	kind?: string;
	/** Where the document appears to grow from, in film coordinates. */
	origin?: {x: number; y: number};
	width?: number;
	/**
	 * Fixed sheet height. Omit it and the sheet takes the height of its
	 * content, which is almost always what you want: a hand-tuned height that
	 * is 100px too tall reads as a half-empty document, and the only way to
	 * catch that is to render a still and look.
	 */
	height?: number;
	zoom?: {at: number; scale: number; x: number; y: number};
	children?: React.ReactNode;
}> = ({
	at,
	title,
	subtitle,
	kind = 'Generated by Mia',
	origin,
	width = 1180,
	height,
	zoom,
	children,
}) => {
	const frame = useCurrentFrame();

	const app = interpolate(frame, [at, at + 26], [0, 1], {
		extrapolateLeft: 'clamp',
		extrapolateRight: 'clamp',
		easing: EASE.out,
	});

	const auto = height === undefined;
	const cx = 960;
	const cy = 566;
	const ox = origin ? origin.x - cx : 0;
	const oy = origin ? origin.y - cy : 0;

	const z = zoom
		? interpolate(frame, [zoom.at, zoom.at + 72], [0, 1], {
				extrapolateLeft: 'clamp',
				extrapolateRight: 'clamp',
				easing: EASE.inOut,
			})
		: 0;

	const scale = (0.86 + app * 0.14) * (1 + (zoom ? (zoom.scale - 1) * z : 0));
	const tx = ox * (1 - app) - (zoom ? (zoom.x - cx) * z * (zoom.scale - 1) : 0);
	const ty = oy * (1 - app) - (zoom ? (zoom.y - cy) * z * (zoom.scale - 1) : 0);

	return (
		<>
			<div
				style={{
					position: 'absolute',
					inset: 0,
					background: 'rgba(24,29,40,0.30)',
					backdropFilter: 'blur(2px)',
					opacity: app,
				}}
			/>
			<div
				style={{
					position: 'absolute',
					left: cx - width / 2,
					top: auto ? cy : cy - height / 2,
					width,
					height,
					maxHeight: 952,
					borderRadius: R.lg,
					background: C.paper,
					boxShadow: SHADOW.float,
					overflow: 'hidden',
					fontFamily: FONT,
					opacity: app,
					transform: `translate(${tx}px, ${ty}px) ${auto ? 'translateY(-50%)' : ''} scale(${scale})`,
					display: 'flex',
					flexDirection: 'column',
				}}
			>
				<div
					style={{
						padding: '20px 28px',
						borderBottom: `1px solid ${C.line}`,
						display: 'flex',
						alignItems: 'center',
						gap: 14,
						flexShrink: 0,
					}}
				>
					<div
						style={{
							width: 38,
							height: 38,
							borderRadius: R.sm,
							background: C.brandSoft,
							display: 'flex',
							alignItems: 'center',
							justifyContent: 'center',
						}}
					>
						<svg width={20} height={20} viewBox="0 0 22 22">
							<path
								d="M6 2.6h7l4 4v12.8a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V3.6a1 1 0 0 1 1-1Z"
								fill="#fff"
								stroke={C.brand}
								strokeWidth="1.6"
								strokeLinejoin="round"
							/>
							<path d="M13 2.8V6.8h4" fill="none" stroke={C.brand} strokeWidth="1.6" strokeLinejoin="round" />
						</svg>
					</div>
					<div style={{flex: 1}}>
						<div style={{fontSize: 20, fontWeight: 600, color: C.ink}}>{title}</div>
						{subtitle ? <div style={{fontSize: 14, color: C.mute, marginTop: 2}}>{subtitle}</div> : null}
					</div>
					<div
						style={{
							display: 'flex',
							alignItems: 'center',
							gap: 8,
							padding: '6px 13px',
							borderRadius: 999,
							background: C.brandSoft,
							color: C.brand,
							fontSize: 13,
							fontWeight: 600,
						}}
					>
						<svg width={13} height={13} viewBox="0 0 13 13">
							<path d="M6.5 1 8 4.9l4 1.6-4 1.6L6.5 12 5 8.1 1 6.5l4-1.6Z" fill={C.brand} />
						</svg>
						{kind}
					</div>
				</div>

				<div style={{flex: 1, minHeight: 0, overflow: 'hidden'}}>{children}</div>
			</div>
		</>
	);
};

/** A spreadsheet grid, for the requirements workbook. */
export const SheetGrid: React.FC<{
	columns: {label: string; w: number}[];
	rows: (string | {v: string; tone?: 'warn' | 'ok' | 'brand'})[][];
	revealFrom?: number;
	/**
	 * Frames between one row landing and the next starting. The default suits a
	 * six-row sheet in a long shot. A ten-row sheet in a three-second shot needs
	 * this down at 3 or the last rows never arrive before the cut.
	 */
	revealStep?: number;
}> = ({columns, rows, revealFrom = 0, revealStep = 4}) => {
	const frame = useCurrentFrame();
	const tpl = columns.map((c) => `${c.w}px`).join(' ');

	return (
		<div style={{fontFamily: FONT}}>
			<div
				style={{
					display: 'grid',
					gridTemplateColumns: tpl,
					background: '#F4F6FA',
					borderBottom: `1px solid ${C.line}`,
				}}
			>
				{columns.map((c) => (
					<div
						key={c.label}
						style={{
							padding: '12px 16px',
							fontSize: 12.5,
							fontWeight: 600,
							letterSpacing: '0.08em',
							color: C.mute,
							borderRight: `1px solid ${C.line}`,
						}}
					>
						{c.label}
					</div>
				))}
			</div>
			{rows.map((r, i) => {
				const app = revealFrom
					? interpolate(frame, [revealFrom + i * revealStep, revealFrom + i * revealStep + 16], [0, 1], {
							extrapolateLeft: 'clamp',
							extrapolateRight: 'clamp',
							easing: EASE.out,
						})
					: 1;
				return (
					<div
						key={i}
						style={{
							display: 'grid',
							gridTemplateColumns: tpl,
							borderBottom: `1px solid ${C.lineSoft}`,
							opacity: app,
							transform: `translateY(${(1 - app) * 6}px)`,
						}}
					>
						{r.map((cell, j) => {
							const v = typeof cell === 'string' ? cell : cell.v;
							const tone = typeof cell === 'string' ? undefined : cell.tone;
							const col =
								tone === 'warn' ? C.warn : tone === 'ok' ? C.ok : tone === 'brand' ? C.brand : C.body;
							const bg =
								tone === 'warn' ? C.warnSoft : tone === 'ok' ? C.okSoft : tone === 'brand' ? C.brandSoft : 'transparent';
							return (
								<div
									key={j}
									style={{
										padding: '13px 16px',
										fontSize: 14.5,
										color: col,
										background: bg,
										borderRight: `1px solid ${C.lineSoft}`,
										lineHeight: 1.35,
										fontWeight: tone ? 600 : 400,
									}}
								>
									{v}
								</div>
							);
						})}
					</div>
				);
			})}
		</div>
	);
};
