'use strict';

/**
 * note-writer.js — render and persist notes, organized by channel.
 *
 * Layout:
 *   <outputDir>/
 *     _library.md                      (index of all channels)
 *     <Channel Name>/
 *       _index.md                      (index of that channel's notes)
 *       <uploaddate>-<slug>.md         (one note per video)
 *       transcripts/<id>.txt           (optional raw transcript sidecar)
 */

const fs = require('node:fs');
const path = require('node:path');

const { ensureDir, safeSegment, slugify, todayStamp, formatDuration } = require('./util');

/* ------------------------------------------------------------------ *
 * Render
 * ------------------------------------------------------------------ */

function frontmatter(obj) {
  const esc = (v) => String(v).replace(/"/g, '\\"');
  const lines = ['---'];
  for (const [k, v] of Object.entries(obj)) {
    if (v === undefined || v === null || v === '') continue;
    if (Array.isArray(v)) lines.push(`${k}: [${v.map((x) => `"${esc(x)}"`).join(', ')}]`);
    else if (typeof v === 'number') lines.push(`${k}: ${v}`);
    else lines.push(`${k}: "${esc(v)}"`);
  }
  lines.push('---');
  return lines.join('\n');
}

/**
 * Render a complete note (markdown string).
 */
function renderNote({ meta, summary, transcript, config = {} }) {
  const captured = todayStamp();
  const dur = formatDuration(meta.durationSec);
  const fm = frontmatter({
    title: meta.title,
    channel: meta.channel,
    youtube_id: meta.id,
    url: meta.webpageUrl,
    uploaded: meta.uploadDate,
    duration: dur,
    captured,
    transcript_source: summary.providerUsed === 'extractive' ? (transcript.source || '') : (transcript.source || ''),
    summary_provider: summary.providerUsed,
    summary_model: summary.model || '',
    style: config.summaryStyle || 'ragnar',
    tags: ['youtube', 'notes', slugify(meta.channel)],
  });

  const header =
    `# ${meta.title}\n\n` +
    `**Channel:** ${meta.channel}` +
    (meta.uploadDate ? ` · **Uploaded:** ${meta.uploadDate}` : '') +
    ` · **Duration:** ${dur} · [Watch ▶](${meta.webpageUrl})\n\n` +
    `> Captured ${captured} · transcript: **${transcript.source || 'n/a'}**` +
    (transcript.translated ? ' (translated)' : '') +
    ` · summary: **${summary.providerUsed}**` +
    (summary.truncated ? ' · _transcript truncated for length_' : '') +
    '\n';

  const parts = [fm, '', header, summary.body.trim(), ''];

  if (config.includeTranscript !== false && transcript.text) {
    parts.push(
      '---',
      '',
      `<details>`,
      `<summary>📄 Full transcript (${transcript.source || 'captions'}${transcript.lang ? ', ' + transcript.lang : ''})</summary>`,
      '',
      transcript.text.trim(),
      '',
      `</details>`,
      ''
    );
  }

  parts.push(
    '---',
    `<sub>Generated by YouTube Notes Studio · ${captured}</sub>`,
    ''
  );

  return parts.join('\n');
}

/* ------------------------------------------------------------------ *
 * Persist
 * ------------------------------------------------------------------ */

/**
 * Write a note to disk under the channel folder. Idempotent per video id:
 * re-running the same link overwrites its note rather than duplicating.
 * @returns {{path:string, channelDir:string, channel:string}}
 */
function writeNote({ meta, summary, transcript, config = {}, outputDir }) {
  const root = ensureDir(outputDir);
  const channel = safeSegment(meta.channel, 'Unknown Channel');
  const channelDir = ensureDir(path.join(root, channel));

  const datePrefix = meta.uploadDate || todayStamp();
  const baseSlug = slugify(meta.title, meta.id);
  let fileName = `${datePrefix}-${baseSlug}.md`;
  let filePath = path.join(channelDir, fileName);

  // Collision handling: if a note exists for a DIFFERENT video, disambiguate
  // with the id; if it's the SAME video, overwrite (regeneration).
  if (fs.existsSync(filePath)) {
    const existingId = readFrontmatterField(filePath, 'youtube_id');
    if (existingId && existingId !== meta.id) {
      fileName = `${datePrefix}-${baseSlug}-${meta.id}.md`;
      filePath = path.join(channelDir, fileName);
    }
  }

  fs.writeFileSync(filePath, renderNote({ meta, summary, transcript, config }), 'utf8');

  // Optional raw transcript sidecar(s).
  const exportFormats = Array.isArray(config.exportTranscript) ? config.exportTranscript : [];
  if (exportFormats.length && transcript.segments && transcript.segments.length) {
    const tdir = ensureDir(path.join(channelDir, 'transcripts'));
    if (exportFormats.includes('txt')) {
      fs.writeFileSync(path.join(tdir, `${meta.id}.txt`), transcript.plain || '', 'utf8');
    }
    if (exportFormats.includes('srt')) {
      fs.writeFileSync(path.join(tdir, `${meta.id}.srt`), segmentsToSrt(transcript.segments), 'utf8');
    }
  }

  // NOTE: the channel index is NOT rebuilt here. With concurrency, two notes
  // from the same channel could race on _index.md. The pipeline rebuilds all
  // indexes once at the end via rebuildAllIndexes(). For standalone single
  // writes, callers can rebuild explicitly.
  return { path: filePath, channelDir, channel };
}

function segmentsToSrt(segments) {
  const fmt = (ms) => {
    const t = Math.max(0, Math.floor(ms));
    const h = Math.floor(t / 3600000);
    const m = Math.floor((t % 3600000) / 60000);
    const s = Math.floor((t % 60000) / 1000);
    const mm = t % 1000;
    const p = (n, w = 2) => String(n).padStart(w, '0');
    return `${p(h)}:${p(m)}:${p(s)},${p(mm, 3)}`;
  };
  return segments
    .map((seg, i) => {
      const end = segments[i + 1] ? segments[i + 1].startMs : seg.startMs + 4000;
      return `${i + 1}\n${fmt(seg.startMs)} --> ${fmt(end)}\n${seg.text}\n`;
    })
    .join('\n');
}

/* ------------------------------------------------------------------ *
 * Indexes
 * ------------------------------------------------------------------ */

function readFrontmatterField(filePath, field) {
  try {
    const head = fs.readFileSync(filePath, 'utf8').split('\n').slice(0, 25);
    for (const line of head) {
      const m = line.match(new RegExp(`^${field}:\\s*"?([^"]*)"?\\s*$`));
      if (m) return m[1];
    }
  } catch {}
  return '';
}

function readNoteMeta(filePath) {
  return {
    title: readFrontmatterField(filePath, 'title'),
    uploaded: readFrontmatterField(filePath, 'uploaded'),
    duration: readFrontmatterField(filePath, 'duration'),
    url: readFrontmatterField(filePath, 'url'),
    provider: readFrontmatterField(filePath, 'summary_provider'),
  };
}

/** Rebuild a channel's _index.md by scanning its notes. */
function rebuildChannelIndex(channelDir, channelName) {
  let files;
  try {
    files = fs.readdirSync(channelDir).filter((f) => f.endsWith('.md') && f !== '_index.md');
  } catch {
    return;
  }
  const rows = files
    .map((f) => {
      const fp = path.join(channelDir, f);
      const m = readNoteMeta(fp);
      return { file: f, ...m };
    })
    .sort((a, b) => (b.uploaded || '').localeCompare(a.uploaded || ''));

  const lines = [
    `# ${channelName} — Notes`,
    '',
    `${rows.length} note${rows.length === 1 ? '' : 's'} · maintained by YouTube Notes Studio`,
    '',
    '| Uploaded | Title | Duration | Watch |',
    '|---|---|---|---|',
  ];
  for (const r of rows) {
    const title = (r.title || r.file.replace(/\.md$/, '')).replace(/\|/g, '\\|');
    lines.push(
      `| ${r.uploaded || '—'} | [${title}](${encodeURI(r.file)}) | ${r.duration || '—'} | ${r.url ? `[▶](${r.url})` : '—'} |`
    );
  }
  lines.push('');
  fs.writeFileSync(path.join(channelDir, '_index.md'), lines.join('\n'), 'utf8');
}

/** Rebuild the top-level _library.md across all channels. */
function rebuildLibraryIndex(outputDir) {
  let dirs;
  try {
    dirs = fs
      .readdirSync(outputDir, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name);
  } catch {
    return;
  }
  const channels = dirs
    .map((name) => {
      const dir = path.join(outputDir, name);
      let count = 0;
      try {
        count = fs.readdirSync(dir).filter((f) => f.endsWith('.md') && f !== '_index.md').length;
      } catch {}
      return { name, count };
    })
    .filter((c) => c.count > 0)
    .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));

  const total = channels.reduce((n, c) => n + c.count, 0);
  const lines = [
    '# 📚 YouTube Notes Library',
    '',
    `${total} note${total === 1 ? '' : 's'} across ${channels.length} channel${channels.length === 1 ? '' : 's'} · updated ${todayStamp()}`,
    '',
    '| Channel | Notes | Index |',
    '|---|---|---|',
  ];
  for (const c of channels) {
    lines.push(`| ${c.name.replace(/\|/g, '\\|')} | ${c.count} | [open](${encodeURI(c.name)}/_index.md) |`);
  }
  lines.push('');
  fs.writeFileSync(path.join(outputDir, '_library.md'), lines.join('\n'), 'utf8');
}

/** Rebuild every channel index plus the library index. Call once after a batch. */
function rebuildAllIndexes(outputDir) {
  let dirs;
  try {
    dirs = fs
      .readdirSync(outputDir, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name);
  } catch {
    return;
  }
  for (const name of dirs) {
    rebuildChannelIndex(path.join(outputDir, name), name);
  }
  rebuildLibraryIndex(outputDir);
}

module.exports = {
  renderNote,
  writeNote,
  rebuildChannelIndex,
  rebuildLibraryIndex,
  rebuildAllIndexes,
};
